version: '3'
services:
  twitch-rec:
    container_name: twitch-rec
    build: .
    restart: always
    volumes:
      - ./recordings:/app/recordings
    environment:
      STREAMER: xxxxx
      QUALITY: best
      INTERVAL: 15
      CLIENT_ID: xxxxx
      CLIENT_SECRET: xxxxx
      PUSHOVER_TOKEN: xxxxx
      PUSHOVER_USER: xxxxx
      TZ: Europe/Paris
